### ISSUE TITLE
Improvement on visibility of replies

### ISSUE THREAD

**Issue by iyupan** [communiteq/discourse-private-replies#4]
Hi,

This is an excellent plugin for discourse to control the visibility of all the replies.

I have constructed a forum based on discourse, and my users require a change visibility of their replies. Specifically, they would like to choose certain users or groups to see their replies, not all the users.

So, would you consider adding such a function to this plugin? I will appreciate it a lot for your consideration.

Thanks, again!

**Comment by communiteq** [comment]
We can provide extra functionality for this plugin as paid work. Please contact us at https://www.communiteq.com/contact/
